[tool.poetry]
name = "timetravel"
version = "0.1.0"
description = ""
authors = ["Amr <akkk33@protonmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
